### ISSUE TITLE
BatchDistributor.vy: Refund excess token (if any) to sender

### ISSUE THREAD

**Issue by jaglinux** [pcaversaccio/snekmate#44]
### Discussed in https://github.com/pcaversaccio/snekmate/discussions/43

<div type='discussions-op-text'>

<sup>Originally posted by **jaglinux** December 31, 2022</sup>
We need to return excess token in distribute_token(), similar to distribute_ether() which refunds excess ether to msg.sender

If this is ok, I will work on the PR to add the code and test case.</div>

**Comment by pcaversaccio** [comment]
There is no such case as excess tokens for `distribute_token` since this works differently as for `msg.value`. There is no native way to handle tokens in the EVM! First you have to approve the amount you want to transfer and thereafter the exact amount is transferred via `transferFrom` during the `distribute_token` function call. Only if all tokens are distributed, the call will succeed. You don't send tokens directly to the contract but it's a combination of `approve` and `distribute_token`.

**Comment by jaglinux** [comment]
Yeah, missed the "total" variable. It ensures that correct token amount is used in `transferFrom`

**Comment by jaglinux** [comment]
To keep the implementation same across the 2 functions,
"Caller gets exact eth refund and not the whole contract balance."
```git diff
diff --git a/src/utils/BatchDistributor.vy b/src/utils/BatchDistributor.vy
index 27fec25..13238d1 100644
--- a/src/utils/BatchDistributor.vy
+++ b/src/utils/BatchDistributor.vy
@@ -51,14 +51,16 @@ def distribute_ether(data: Batch):
            of tuples that contain each a recipient address &
            ether amount in wei.
     """
+    total: uint256 = empty(uint256)
     for txn in data.txns:
         # A low-level call is used to guarantee compatibility
         # with smart contract wallets. As a general pre-emptive
         # safety measure, a reentrancy guard is used.
         raw_call(txn.recipient, b"", value=txn.amount)
+        total += txn.amount
 
-    if (self.balance != empty(uint256)):
-        raw_call(msg.sender, b"", value=self.balance)
+    if (msg.value != total):
+        raw_call(msg.sender, b"", value=msg.value - total)
```
Contract can have more balance if ether is  accidentally sent in constructor. Thats the only possible case. 
Default function prevents unwanted donation anyways.
https://vyper.readthedocs.io/en/stable/control-structures.html?highlight=__default__#the-default-function
_Just as in Solidity, Vyper generates a default function if one isn’t found, in the form of a REVERT call. Note that this still [generates an exception](https://github.com/ethereum/wiki/wiki/Subtleties) and thus will not succeed in receiving funds._

This is an edge case, we can ignore it. Based on reply, I will close the issue.

**Comment by pcaversaccio** [comment]
@jaglinux this is only one way to force ether into the contract. There are other ways that bypass the `nonpayable` `__default__` feature. You can force ether into a contract using `selfdestruct` (since the destination account code - in this case the `BatchDistributor` is not executed), or you can set the address of the `BatchDistributor` as your `coinbase` address (i.e. the fee recipient of your staking rewards) - also in this case the ether is forced into the contract. The third possibility would be, that you deploy the `BatchDistributor` via `CREATE2`. In that case, you can pre-compute the address where `BatchDistributor` will be deployed, send there some ether, and deploy `BatchDistributor` thereafter. Tada, you got some excess ether locked. As you can see there are plenty of use cases that cannot be prevented at all, and if people force ether into this contract for any weird reason, the first calling `distribute_ether` will receive some excess ether. I don't think this justifies the additional costs of opcodes tracking `total`. Therefore, I will close this issue.

**Comment by pcaversaccio** [comment]
In order to reflect this discussion in the codebase, I quickly added a comment via https://github.com/pcaversaccio/snekmate/commit/d2d8b9ba706269611e2c17055dd6f6ae04878e43.

**Comment by jaglinux** [comment]
Thanks for the explanation ! appreciate this is captured in codebase.
