### ISSUE TITLE
Failed Signature Recovery (`ECDSA`)

### ISSUE THREAD

**Issue by z80dev** [pcaversaccio/snekmate#62]
### Describe the issue:

I'm working on some signature verification code in Vyper and consistently failing to recover the correct signer address when using ECDSA.vy's `recover_sig` function.

I have deployed `ECDSA.vy` to goerli at `0xAdf31a3b9B9DD0486199A1029BEb8bA4Cc86e5E4`

Here are the inputs I am using:

`cast keccak 1234` outputs 0x387a8233c96e1fc0ad5e284353276177af2186e7afa85296f106336e376669f7

I now want to sign this hash, and use ECDSA.vy to recover the address used to sign.

I am using wagmi.sh's components to generate a signature on my frontend. I input the above hash into the frontend widget, then sign, and the frontend widget recovers my signature as expected after I confirm and sign with my wallet (screenshot attached). You can access this same widget [here](https://wagmi.sh/examples/sign-message)

![frontend screenshot](https://imgur.com/lJnFQKb.png)

I then take the signature provided to me by the widget and call:

```
In [6]: e.recover_sig("0x387a8233c96e1fc0ad5e284353276177af2186e7afa85296f106336e376669f7", "0x042f669e124b91b5c975d3bc329618373ee0bc666c6412891ff6d85e7e0cf7ae4f9630450253ac55784fc534c655ff2e3743e04df2a5035728ecede196a379311c")
Out[6]: '0xbA3De837Da49408AD799d6B7ffD40a013B7214FB'
```

I *was* able to run `forge test --match-contract ECDSA` successfully, and the tests pass, but this failing example here is so minimal that I have no idea what else to try.

### Code example to reproduce the issue:

see `ECDSA.vy`

### Version:

0.3.7+commit.6020b8b

**Comment by pcaversaccio** [comment]
@z80dev I can reproduce your issue but can also resolve it :-D. So the underlying issue is that you don't use a [`EIP-191`](https://eips.ethereum.org/EIPS/eip-191) signature in `recover_sig`. So let me explain what you need to do:

- I sign the message `0x387a8233c96e1fc0ad5e284353276177af2186e7afa85296f106336e376669f7`
![image](https://user-images.githubusercontent.com/25297591/213661498-16b1ead5-cd8a-47d8-b8d3-23c902f51723.png)

- I call `to_eth_signed_message_hash` in the contract (I verified it quickly on Etherscan), using the `0x387a8233c96e1fc0ad5e284353276177af2186e7afa85296f106336e376669f7` payload from above:
![image](https://user-images.githubusercontent.com/25297591/213661689-20405a05-9eed-456e-b8a2-b47ec88b9ac4.png)

- I call `recover_sig` with the signature from step one and the output from step 2 and it will work :-D: 
![image](https://user-images.githubusercontent.com/25297591/213662718-62b8da96-6392-4799-9fcf-4050b53c46bd.png)

I also document this behavior in the natspec section of the code btw 

![image](https://user-images.githubusercontent.com/25297591/213662882-1f572a70-8e70-4121-aa53-86037f6b3344.png)


Of course, you can also fix that on the client side where it should return the correct `EIP-191` signed message. I recommend reading e.g. how [ethers](https://docs.ethers.org/v5/api/signer/#Signer-signMessage) signs a message: 

![image](https://user-images.githubusercontent.com/25297591/213663268-4aa927a0-2ae3-4b99-86a1-6e56ed400ecb.png)

**Comment by jaglinux** [comment]
@pcaversaccio , The signature displayed in the wagmi app does not match with the signature you provided in third step.
How did you derive the signature ?
I used web3.eth.accounts.sign() to generate the signature and validated the signature with the steps you mentioned.
The contract (ECDSA.vy) works perfectly. 
But I am not able to understand the signature displayed by the wagmi app.

**Comment by pcaversaccio** [comment]
@jaglinux oops yes that's a mistake from my side. So in order to verify it I used Etherscan's https://etherscan.io/verifiedSignatures# website which is bullet-proof. From there I take the signature in step 3. 
![image](https://user-images.githubusercontent.com/25297591/213674621-d9d55b5f-5219-462d-906a-3b1eb93d92d8.png)

As you can see it's different from the wagmi app.
![image](https://user-images.githubusercontent.com/25297591/213674682-bad05ed4-177a-4c61-9488-77073451f0e6.png)

Yes if you use `web3.eth.accounts.sign()` or ethers (or Etherscan or MyEtherWallet or MyCrypto etc.) it works as intended. So most probably there is something weird on the wagmi app side. I will try to quickly check their code.

**Comment by pcaversaccio** [comment]
I think I found the issue - WAGMI treats the user input as `string`: https://github.com/wagmi-dev/wagmi/blob/main/docs/components/examples/SignMessage.tsx#L38. They also use ethers `signMessage` function: https://github.com/wagmi-dev/wagmi/blob/main/packages/core/src/actions/accounts/signMessage.ts#L20. However, we would actually need to sign the **bytes** version of it! This is also described in the ethers docs: 
![image](https://user-images.githubusercontent.com/25297591/213688729-f8e290c2-c445-4157-8c51-49ae2fb2bb39.png)

So my recommendation here is either use Etherscan or MEW to sign the data because they treat the input correctly or use directly web3 or ethers. WAGMI assumes only a string input. As a simple example where the signatures match for WAGMI & Etherscan.

![image](https://user-images.githubusercontent.com/25297591/213689108-eae38842-2e2b-428c-9c0c-be4ae0debec7.png)
![image](https://user-images.githubusercontent.com/25297591/213689120-73cc166f-b810-4941-9cf0-b4127d1064b2.png)

Maybe also explain why this is very important and you should not sign non-hashed data:
![image](https://user-images.githubusercontent.com/25297591/213689635-d5f3ed29-1f98-49c1-b101-e33c38ab3b10.png)

**Comment by jaglinux** [comment]
Thanks @pcaversaccio for explaining in detail, appreciate explaining the WAGMI signing details.
So if a user inputs the string "1234" as data to be signed (not recommended) instead of hash which is bytes32, 
then the Ethereum signed message will be **'\x19Ethereum Signed Message:\n4'** 
4 representing  the length of input data string.

Just to verify, I coded the function `to_eth_signed_message_data` to output the message hash . I took the message hash obtained by calling `to_eth_signed_message_data` + the signature obtained by WAGMI / Etherscan and could successfully verify with `recover_sig`
``` git diff
@external
@pure
def to_eth_signed_message_data(data: String[32], lenData: String[2]) -> bytes32:
    _ethMessage: String[32] = concat("\x19Ethereum Signed Message:\n", lenData)
    return keccak256(concat(_ethMessage, data))
```

If anyone interested to experiment, [contract link on goerli](https://goerli.etherscan.io/address/0x46CB19D9d7444500d69BF43bC4B054Aa2b647b84#readContract)

It will be useful if Wagmi and other apps display both signature and messageHash.

**Comment by pcaversaccio** [comment]
> So if a user inputs the string "1234" as data to be signed (not recommended) instead of hash which is bytes32,
then the Ethereum signed message will be '\x19Ethereum Signed Message:\n4'
4 representing the length of input data string.

The Ethereum signed message will be `keccak256(concat(b"\x19Ethereum Signed Message:\n4", b"1234"))`.

You can see [here](https://github.com/ethers-io/ethers.js/blob/master/packages/hash/src.ts/message.ts) how it's done:

```ts
import { Bytes, concat } from "@ethersproject/bytes";
import { keccak256 } from "@ethersproject/keccak256";
import { toUtf8Bytes } from "@ethersproject/strings";

export const messagePrefix = "\x19Ethereum Signed Message:\n";

export function hashMessage(message: Bytes | string): string {
    if (typeof(message) === "string") { message = toUtf8Bytes(message); }
    return keccak256(concat([
        toUtf8Bytes(messagePrefix),
        toUtf8Bytes(String(message.length)),
        message
    ]));
}
```

> Just to verify, I coded the function to_eth_signed_message_data to output the message hash . I took the message hash obtained by calling to_eth_signed_message_data + the signature obtained by WAGMI / Etherscan

That will only work for non-hashed data as seen above. Etherscan correctly identifies `bytes32` hashes as Bytes input where WAGMI will define it as `string` (e.g. Etherscan will treat `0x387a8233c96e1fc0ad5e284353276177af2186e7afa85296f106336e376669f7` as bytes while WAGMI will do `b"0x387a8233c96e1fc0ad5e284353276177af2186e7afa85296f106336e376669f7"`).

To be fair with WAGMI, it's labelled as "Example" (https://wagmi.sh/examples/sign-message). So anyone should also do it's own research beforehand. Feel free to open an issue there however :-D.

**Comment by jaglinux** [comment]
> To be fair with WAGMI, it's labelled as "Example" (https://wagmi.sh/examples/sign-message). So anyone should also do it's own research beforehand. Feel free to open an issue there however :-D.

Yes, I got that point. Wagmi app accepts only string and there is no way to pass bytes, in this case hash.
Its about displaying both signature and messageHash in the display window of these apps.
So that user can verify on their own.  Maybe there is a security concern, possible replay attack ?
This issue was created because OP did not have the messageHash data from these apps.
(Maybe I should fork and add this feature !)

**Comment by pcaversaccio** [comment]
I think it would be a good idea to open an issue & a related PR and discuss the ideas. Displaying the correct Ethereum signed message hash as well as the signature would be definitely a value-add imho.
